language: php
php:
- 5.4
- 5.5
- 5.6
install:
- travis_retry composer self-update
- travis_retry composer install
before_script:
- phpenv rehash
script:
- phpunit
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
